local conf={
    shells={
        {
            display="cmd",
            factory="ConPTYShellContextFactory",
            cmd=[[cmd]],
            codepage=932,
            fontsize=16.0,
            fonts={"Cica"}
        },
        {
            display="cmd(admin)",
            factory="ConPTYShellContextFactory",
            admin=true,
            cmd=[[cmd]],
            codepage=932,
            fontsize=16.0,
            fonts={"Cica"}
        },
        {
            display="cmd(ConsoleRead)",
            factory="ConsoleReadShellContextFactory",
            cmd=[[cmd]],
            codepage=932,
            fontsize=16.0,
            font="Cica"
        },
        {
            display="cmd(ConsoleRead&admin)",
            factory="ConsoleReadShellContextFactory",
            admin=true,
            cmd=[[cmd]],
            codepage=932,
            fontsize=16.0,
            font="Cica"
        },
    },
    initshell=3
}

return conf